### ISSUE TITLE
Add Captcha

### ISSUE THREAD

**Issue by hiddify** [iranxray/hope-toolbox#5]
Please add captcha to your site, because your toolbox can be used by bots ;)

**Comment by iranxray** [comment]
ممنون. ما درخواست‌ها رو بر مبنای IP محدود می‌کنیم. فکر می‌کنیم این روش برای کاربر ساده‌تر باشه و در عین حال جلوی بات‌ها هم گرفته بشه.

**Comment by nimaaskarian** [comment]
> ممنون. ما درخواست‌ها رو بر مبنای IP محدود می‌کنیم. فکر می‌کنیم این روش برای کاربر ساده‌تر باشه و در عین حال جلوی بات‌ها هم گرفته بشه.

پروکسی لیست

**Comment by iranxray** [comment]
@nimaaskarian منظورتون چیه؟

**Comment by nimaaskarian** [comment]
@iranxray 
منظورم اینه که با پروکسی لیست میشه محدود کردن درخواست ها بر مبنای IP رو دور زد. اگه از کپچا استفاده کنی احتمال اینکه مشکلی پیش بیاد کمتر میشه. اشتباه میکنم!؟
